# Generated by Django 5.2.1 on 2025-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
