# Generated by Django 5.2.1 on 2025-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0002_project_description_en_project_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ManyToManyField(blank=True, null=True, related_name='avatar_skill', to='freelance_app.skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.ManyToManyField(blank=True, null=True, related_name='skill_bio', to='freelance_app.skill'),
        ),
    ]
